<?php

namespace RPI\Framework\Test\RPI\Framework\Services;

/**
 * Test class for Service.
 * Generated by PHPUnit on 2012-11-23 at 12:31:13.
 */
class ServiceTest extends \RPI\Framework\Test\Base
{
    /**
     * @var Service
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        // TODO: need to create test concreate object to test
        //$this->object = new \RPI\Framework\Services\Service;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
