<?php

namespace RPI\Framework\Test\RPI\Framework\WebService;

/**
 * Test class for Response.
 * Generated by PHPUnit on 2012-11-23 at 12:34:39.
 */
class ResponseTest extends \RPI\Framework\Test\Base
{
    /**
     * @var Response
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        
        $this->object = new \RPI\Framework\WebService\Response;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
