<?php

namespace RPI\Framework\Test\RPI\Framework\WebService;

/**
 * Test class for ResponseStatus.
 * Generated by PHPUnit on 2012-11-23 at 12:34:48.
 */
class ResponseStatusTest extends \RPI\Framework\Test\Base
{
    /**
     * @var ResponseStatus
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \RPI\Framework\WebService\ResponseStatus;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
