<?php

namespace RPI\Framework\Test\RPI\Framework\WebService;

/**
 * Test class for Server.
 * Generated by PHPUnit on 2012-11-23 at 12:34:54.
 */
class ServerTest extends \RPI\Framework\Test\Base
{
    /**
     * @var Server
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        // TODO: create concreate class to test this:
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
