<?php

namespace RPI\Framework\Test\Form\Validator;

/**
 * Test class for Standard.
 * Generated by PHPUnit on 2012-12-06 at 22:29:10.
 */
class StandardTest extends \RPI\Test\Harness\Base
{
    /**
     * @var Standard
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    
    public function test()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
