<?php

namespace RPI\Framework\Test\WebServer\RPI\Framework\Form;

/**
 * Test class for Button.
 * Generated by PHPUnit on 2012-12-06 at 22:26:13.
 */
class ButtonTest extends \RPI\Framework\Test\Base
{
    /**
     * @var Button
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testSetParent().
     */
    public function testSetParent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
