<?php

namespace RPI\Framework\Test\RPI\Framework\Form\Validator;

/**
 * Test class for RegularExpression.
 * Generated by PHPUnit on 2012-12-06 at 22:29:10.
 */
class RegularExpressionTest extends \RPI\Test\Harness\Base
{
    /**
     * @var RegularExpression
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testValidate().
     */
    public function testValidate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
