<?php

namespace RPI\Framework\Test\RPI\Framework\Views\Php;

/**
 * Test class for View.
 * Generated by PHPUnit on 2012-11-23 at 12:32:51.
 */
class ViewTest extends \RPI\Framework\Test\Base
{
    /**
     * @var View
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        
        // TODO: need to create a PHP view class to test this
        //$this->object = new \RPI\Framework\Views\Php\View(
        //);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testRender().
     */
    public function testRender()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
