<?php

namespace RPI\Framework\Test\WebService;

/**
 * Test class for Response.
 * Generated by PHPUnit on 2012-11-23 at 12:34:39.
 */
class ResponseTest extends \RPI\Test\Harness\Base
{
    /**
     * @var Response
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        
        //$this->object = new \RPI\Framework\WebService\Response;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    
    public function test()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
