<?php

namespace RPI\Framework\Test\WebServer\RPI\Framework\Form\FormItem;

/**
 * Test class for Checkbox.
 * Generated by PHPUnit on 2012-12-06 at 22:27:58.
 */
class CheckboxTest extends \RPI\Framework\Test\Base
{
    /**
     * @var Checkbox
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
