<?php

namespace RPI\Framework\Test\WebServer\RPI\Framework\Exceptions;

/**
 * Test class for Duplicate.
 * Generated by PHPUnit on 2012-11-23 at 14:40:30.
 */
class DuplicateTest extends \RPI\Framework\Test\Base
{
    /**
     * @var Duplicate
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \RPI\Framework\Exceptions\Duplicate;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
