<?php

namespace RPI\Framework\Test\Helpers;

/**
 * Test class for HTML.
 * Generated by PHPUnit on 2012-12-03 at 12:44:35.
 */
class HTMLTest extends \RPI\Test\Harness\Base
{
    /**
     * @var HTML
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testParseHTML().
     */
    public function testParseHTML()
    {
        $source = <<<EOT
            <p>
                1. dwqdq dwd <nontag>no tag text</nontag> <font>font tag text</font>
            </p>

            <p>
                2. dwqdq<br/><br/><br/> dwd dwqh ioh iodwq<br/>
            </p>

            <p>
                3. dwqdq<br/><br/> dwd <nontag>no tag text</nontag> <font>font tag text</font>
            </p>

            4. dqwdqw <strong>qdwq</strong> wqd!!

            <strong>5. dqw</strong>dqw <strong>qdwq</strong> wqd!!

            6. dqwdqw <strong>qdwq</strong> wqd<em>!!</em>

            <nontag>7. dqw</nontag>dqw <strong>qdwq</strong> wqd!!

            <strong>8. dqw</strong>dqw <strong>qdwq</strong> wqd<em>!!</em>

            <strong>9. dqw</strong>dqw <br/><strong>qdwq</strong> wqd<em>!!</em>

            <div>x<i>10. dwqd</i>dqwdqw <strong>qdwq</strong> wqd!!</div>
EOT;

        $htmlResult = \RPI\Framework\Helpers\HTML::sanitise($source);
        var_dump($htmlResult);

        $d = new \DOMDocument();
        $d->loadXML("<body xmlns=\"http://www.w3.org/1999/xhtml\">".$htmlResult."</body>");

        $sourceDocument = new \DOMDocument();
        $expectedResult = <<<EOT
            <p>
                1. dwqdq dwd no tag text font tag text
            </p>
            <p>
                2. dwqdq dwd dwqh ioh iodwq
            </p>
            <p>
                3. dwqdq dwd no tag text font tag text
            </p>
            4. dqwdqw <strong>qdwq</strong> wqd!!

            <strong>5. dqw</strong>dqw <strong>qdwq</strong> wqd!!

            6. dqwdqw <strong>qdwq</strong> wqd<em>!!</em>

            7. dqwdqw <strong>qdwq</strong> wqd!!

            <strong>8. dqw</strong>dqw <strong>qdwq</strong> wqd<em>!!</em>

            <strong>9. dqw</strong>dqw <strong>qdwq</strong> wqd<em>!!</em>            
            <p>
                x<em>10. dwqd</em>dqwdqw <strong>qdwq</strong> wqd!!
            </p>
EOT;
        $sourceDocument->loadXML("<body xmlns=\"http://www.w3.org/1999/xhtml\">".$expectedResult."</body>");

        $this->assertEqualXMLStructure($sourceDocument->documentElement, $d->documentElement);
    }

    /**
     * @todo Implement testConvertFromText().
     */
    public function testConvertFromText()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
