<?php

namespace RPI\Framework\Test\Helpers;

/**
 * Test class for View.
 * Generated by PHPUnit on 2012-06-25 at 09:43:21.
 */
class ViewTest extends \RPI\Test\Harness\Base
{
    /**
     * @var View
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetDataView().
     */
    public function testGetDataView()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetDataViewId().
     */
    public function testGetDataViewId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
