<?php

namespace RPI\Framework\Test\RPI\Framework\Helpers;

/**
 * Test class for Crypt.
 * Generated by PHPUnit on 2012-12-06 at 22:12:29.
 */
class CryptTest extends \RPI\Framework\Test\Base
{
    /**
     * @var Crypt
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testEncrypt().
     */
    public function testEncrypt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDecrypt().
     */
    public function testDecrypt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
