<?php

namespace RPI\Framework\Test\RPI\Framework\Helpers;

/**
 * Test class for Locking.
 * Generated by PHPUnit on 2012-06-25 at 09:43:06.
 */
class LockingTest extends \RPI\Framework\Test\Base
{
    /**
     * @var Locking
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testLock().
     */
    public function testLock()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testRelease().
     */
    public function testRelease()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
