<?php

namespace RPI\Framework\Test\RPI\Framework\Helpers;

/**
 * Test class for Pagination.
 * Generated by PHPUnit on 2012-12-04 at 16:07:02.
 */
class PaginationTest extends \RPI\Framework\Test\Base
{
    /**
     * @var Pagination
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testInsertPagination().
     */
    public function testInsertPagination()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
