<?php

namespace RPI\Framework\Test\RPI\Framework\Helpers;

/**
 * Test class for Reflection.
 * Generated by PHPUnit on 2012-06-25 at 09:43:11.
 */
class ReflectionTest extends \RPI\Framework\Test\Base
{
    /**
     * @var Reflection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testCreateObject().
     */
    public function testCreateObject()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testCreateObjectByClassInfo().
     */
    public function testCreateObjectByClassInfo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
