<?php

namespace RPI\Framework\Test\WebServer\RPI\Framework\WebService;

/**
 * Test class for Client.
 * Generated by PHPUnit on 2012-11-23 at 12:33:31.
 */
class ClientTest extends \RPI\Framework\Test\Base
{
    /**
     * @var Client
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \RPI\Framework\WebService\Client(
            null
        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testAuthenticate().
     */
    public function testAuthenticate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
