<?php

namespace RPI\Framework\Test\WebServer\RPI\Framework\WebService;

/**
 * Test class for Context.
 * Generated by PHPUnit on 2012-11-23 at 12:33:36.
 */
class ContextTest extends \RPI\Framework\Test\Base
{
    /**
     * @var Context
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \RPI\Framework\WebService\Context;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
