<?php

namespace RPI\Framework\Test\WebServer\RPI\Framework\Form\Validator\Standard;

/**
 * Test class for Type.
 * Generated by PHPUnit on 2012-12-06 at 22:26:17.
 */
class TypeTest extends \RPI\Framework\Test\Base
{
    /**
     * @var Type
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \RPI\Framework\Form\Validator\Standard\Type;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
