<?php

namespace RPI\Framework\Test\RPI\Framework\WebService\Exceptions;

/**
 * Test class for MissingMethod.
 * Generated by PHPUnit on 2012-11-23 at 14:45:08.
 */
class MissingMethodTest extends \RPI\Framework\Test\Base
{
    /**
     * @var MissingMethod
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \RPI\Framework\WebService\Exceptions\MissingMethod;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
