<?php

namespace RPI\Framework\Test\RPI\Framework\WebService\Exceptions;

/**
 * Test class for WebService.
 * Generated by PHPUnit on 2012-11-23 at 14:45:09.
 */
class WebServiceTest extends \RPI\Test\Harness\Base
{
    /**
     * @var WebService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        
        // TODO: create concreate class to test this:
        //$this->object = new \RPI\Framework\WebService\Exceptions\WebService;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetLocalizedMessage().
     */
    public function testGetLocalizedMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
