<?php

namespace RPI\Framework\Test\RPI\Framework\Form\FormItem;

/**
 * Test class for Date.
 * Generated by PHPUnit on 2012-12-06 at 22:27:59.
 */
class DateTest extends \RPI\Framework\Test\Base
{
    /**
     * @var Date
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
