<?php

namespace RPI\Framework\Test\RPI\Framework\Form\FormItem;

/**
 * Test class for Select.
 * Generated by PHPUnit on 2012-12-06 at 22:27:59.
 */
class SelectTest extends \RPI\Framework\Test\Base
{
    /**
     * @var Select
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
