<?php

namespace RPI\Framework\Test\WebServer\RPI\Framework\WebService\Exceptions;

/**
 * Test class for Generic.
 * Generated by PHPUnit on 2012-11-23 at 14:45:08.
 */
class GenericTest extends \RPI\Framework\Test\Base
{
    /**
     * @var Generic
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \RPI\Framework\WebService\Exceptions\Generic;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
