<?php

namespace RPI\Framework\Test\RPI\Framework\Exceptions;

/**
 * Test class for NotImplemented.
 * Generated by PHPUnit on 2012-11-23 at 14:40:31.
 */
class NotImplementedTest extends \RPI\Framework\Test\Base
{
    /**
     * @var NotImplemented
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \RPI\Framework\Exceptions\NotImplemented;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
