<?php

namespace RPI\Framework\Test\App;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-20 at 18:51:24.
 */
class DebugTest extends \RPI\Test\Harness\Base
{
    /**
     *
     * @var \RPI\Framework\App 
     */
    private $app = null;

    /**
     * @var Debug
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        
        $this->app = new \RPI\Framework\App(
            $this->logger,
            dirname(__FILE__)."/Conf/debug.test.config",
            null,
            new \RPI\Foundation\Cache\Data\Mock()
        );
        
        $this->object = new \RPI\Framework\App\Debug(
            $this->logger,
            $this->app
        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers RPI\Framework\App\Debug::log
     */
    public function testLog()
    {
        $this->assertFalse($this->object->log("Test"));
    }
}
