<?php

namespace RPI\Framework\Test\RPI\Framework;

/**
 * Test class for Component.
 * Generated by PHPUnit on 2012-11-23 at 12:37:14.
 */
class ComponentTest extends \RPI\Framework\Test\Base
{
    /**
     * @var Component
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        // TODO: create concreate class to test this:
        //$this->object = new \RPI\Framework\Component;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testProcess().
     */
    public function testProcess()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testCreateComponentFromViewData().
     */
    public function testCreateComponentFromViewData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
