<?php

namespace RPI\Framework\Test\Form\FormItem\Radio;

/**
 * Test class for Option.
 * Generated by PHPUnit on 2012-12-06 at 22:26:17.
 */
class OptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Option
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        
        //$this->object = new \RPI\Framework\Form\FormItem\Radio\Option;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    
    public function test()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
